package com.example.social.presentation.navigation

object Routes {
    const val LOGIN = "login"
    const val HOME = "home"
    const val REGISTER = "register"
    const val TABS = "tabs"
    const val FRIEND= "friend"
    const val ALL_FRIEND_REQ = "all_friend_req"
    const val ALL_FRIEND_SEND = "all_friend_send"
    const val PROFILE_SCREEN = "profile_screen"
    const val ALL_FRIEND = "all_friend"
    const val ALL_FRIEND_PROFILE = "all_friend_profile"
    const val PROFILE_EDIT = "profile_edit"
    const val  FRIEND_PROFILE= "friend_profile"
    const val STATUS="status"
    const val ALL_FRIEND_OF_FRIEND="all_friend_of_friend"
    const val NOTIFICATION="notification"
    const val POST_FOCUS="post_focus"
    const val SETTING="setting"
    const val NAR_DRAWER = "NarDrawer"
    const val QUAN_LI_USER = "QuanLyUser"
    const val QUAN_LI_POST = "QuanLyBaiDang"
    const val QUAN_LI_MOI_QH = "QuanLyMQH"
    const val THONG_KE = "ThongKe"
    const val CHINH_SUA = "ChinhSua"
    const val POST_FOR_MODERATOR = "Post_For_Moderator"
}